name: "Tests"

on:
  push:
    branches-ignore:
      - "dependabot/**"
      - "sourcery/**"
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  create-test-matrix:
    name: Create Notebook List
    runs-on: ubuntu-latest
    needs: [pre-commit]
    outputs:
      notebook-list: ${{ steps.notebooks.outputs.notebook-list }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set notebook list
        id: notebooks
        shell: python
        run: |
          import json
          import os
          from pathlib import Path
          # looking for the notebook names to skip
          block_list =[
              "CK-case-study",
              "sim-case-study",
              "PCP-case-study-pretty",
              "PS1_pyglotaran_equalarea",
          ]

          notebook_paths = []
          for notebook_path in Path().rglob("*.ipynb"):
              if notebook_path.stem not in block_list:
                  notebook_paths.append(
                      {
                          "name": notebook_path.stem,
                          "path": notebook_path.resolve().as_posix(),
                      }
                  )
          with open(os.getenv("GITHUB_OUTPUT"), "a", encoding="utf8") as f:
              f.writelines([f"notebook-list={json.dumps(notebook_paths)}"])

  run-tests:
    name: "Test ${{ matrix.notebook_path.name }}"
    runs-on: ubuntu-latest
    needs: [create-test-matrix]
    strategy:
      matrix:
        notebook_path: ${{fromJson(needs.create-test-matrix.outputs.notebook-list)}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install test dependencies
        run: |
          pip install wheel
          pip install -r .github/test-requirements.txt
      - name: Testing ${{ matrix.notebook_path.name }}
        run: python -m pytest --nbval-lax ${{ matrix.notebook_path.path }}
      - name: Installed packages
        if: always()
        run: |
          pip freeze
